name: geo_silent
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sound_mode: ^3.0.0
  flutter_svg: ^2.0.9
  permission_handler: ^10.2.0
  google_maps_flutter: ^2.2.0
  geolocator: ^11.0.0
  collection: ^1.18.0
  sqflite: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/permission_denied.svg
    - assets/images/location_markers.svg
    - assets/images/location_markers.bmp
 